# Generated by Django 3.1.5 on 2021-01-11 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('token', models.CharField(default='1234a', max_length=100, primary_key=True, serialize=False, verbose_name='Token')),
                ('bio', models.CharField(default='cool', max_length=100, verbose_name='Bio')),
                ('name', models.CharField(default='...', max_length=100, verbose_name='Nimi')),
                ('location', models.CharField(default='puudub', max_length=25, verbose_name='Elukoht')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('sport', models.CharField(choices=[('jooks', 'Jooksmine'), ('jõud', 'Jõutreening'), ('crossfit', 'Crossfit'), ('kardio', 'Kardio'), ('ratas', 'Ratas'), ('ujumine', 'Ujumine'), ('tennis', 'Tennis'), ('suusatamine', 'Suusatamine'), ('yoga', 'Yoga'), ('muu', 'Muu')], default='jooks', max_length=15, verbose_name='Spordiala')),
                ('image', models.ImageField(default='profile.png', upload_to='profile_pics')),
                ('username', models.CharField(default='puudub', max_length=30, verbose_name='Kasutajanimi')),
                ('is_athlete', models.BooleanField(default=True)),
                ('is_coach', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(default='', max_length=50, verbose_name='KasutajaEmail')),
                ('token', models.CharField(default='1234', max_length=50, verbose_name='Token')),
                ('verified', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Grupinimi')),
                ('sport', models.CharField(choices=[('jooks', 'Jooksmine'), ('jõud', 'Jõutreening'), ('crossfit', 'Crossfit'), ('kardio', 'Kardio'), ('ratas', 'Ratas'), ('ujumine', 'Ujumine')], default='jooks', max_length=10, verbose_name='Spordiala')),
                ('members_count', models.IntegerField(default=0, verbose_name='Liikmete arv')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Kirjeldus')),
                ('image', models.ImageField(default='aigar.jpg', upload_to='traininggroup_covers')),
                ('location', models.CharField(choices=[('Tartu', 'Tartu'), ('Tallinn', 'Tallinn'), ('Pärnu', 'Pärnu'), ('Viljandi', 'Viljandi'), ('Muu', 'Muu')], default='Muu', max_length=100, verbose_name='Asukoht')),
                ('coach_name', models.CharField(default='', max_length=25, verbose_name='Treeneri nimi')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', related_query_name='coach', to='fitex.profile')),
                ('requesting_users', models.ManyToManyField(blank=True, related_name='requesting_users', related_query_name='requesting_users', to='fitex.Profile')),
                ('users', models.ManyToManyField(blank=True, related_name='users', related_query_name='users', to='fitex.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', related_query_name='groups', to='fitex.TrainingGroup'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Treeningu nimetus')),
                ('content', models.TextField(verbose_name='Kirjeldus')),
                ('price', models.CharField(blank=True, max_length=5, null=True, verbose_name='Hind')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('hardness_level', models.TextField(default='raske', max_length=20)),
                ('location', models.CharField(default='', max_length=150, verbose_name='Asukoht')),
                ('city', models.CharField(choices=[('Tartu', 'Tartu'), ('Tallinn', 'Tallinn'), ('Pärnu', 'Pärnu'), ('Viljandi', 'Viljandi'), ('Muu', 'Muu')], default='Muu', max_length=100, verbose_name='Linn/Asula')),
                ('stringdate', models.CharField(default='', max_length=100, verbose_name='JS string date')),
                ('organizeremail', models.EmailField(default='', max_length=254, verbose_name='Organiseerija email')),
                ('organizername', models.CharField(default='', max_length=50, verbose_name='Organiseerija nimi')),
                ('starts', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Algab')),
                ('ends', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Lõppeb')),
                ('starts1', models.CharField(default='12:00', max_length=50, verbose_name='alg')),
                ('ends1', models.CharField(default='13:00', max_length=50, verbose_name='lõpp')),
                ('registrations_made', models.IntegerField(default=0, verbose_name='Registreerunute arv')),
                ('date', models.CharField(default='13.august', max_length=50, verbose_name='kuupäev')),
                ('stringtime', models.CharField(default='', max_length=100, verbose_name='JS string time (date)')),
                ('stringtime2', models.CharField(default='', max_length=100, verbose_name='JS string time (date2)')),
                ('arrive_when', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Millal saabuda')),
                ('registration_limit', models.IntegerField(choices=[(0, 'Pole piirangut'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], default=0, verbose_name='Osavõtjate maksimaalne hulk')),
                ('sport', models.CharField(choices=[('jooks', 'Jooksmine'), ('jõud', 'Jõutreening'), ('crossfit', 'CrossFit'), ('kardio', 'Kardio'), ('spinning', 'Spinning'), ('yoga', 'Yoga'), ('ratas', 'Ratas'), ('ujumine', 'Ujumine'), ('tennis', 'Tennis'), ('suusatamine', 'suusatamine'), ('muu', 'Muu')], default='puudub', max_length=15, verbose_name='Spordiala')),
                ('group', models.CharField(default='avalik', max_length=20, verbose_name='Grupi nimi')),
                ('group_id', models.IntegerField(default=0, verbose_name='Grupi id')),
                ('short_date', models.CharField(default='', max_length=15, verbose_name='Paev/kuu, short date')),
                ('coach', models.ForeignKey(default='no data', on_delete=django.db.models.deletion.CASCADE, to='fitex.profile')),
            ],
            options={
                'verbose_name': 'training',
                'verbose_name_plural': 'trainings',
                'ordering': ['-starts'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_registered', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('event_time', models.CharField(default='', max_length=60)),
                ('event_date', models.CharField(default='', max_length=60)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitex.post', verbose_name='Training')),
                ('profile', models.ForeignKey(default='no data', on_delete=django.db.models.deletion.CASCADE, to='fitex.profile', verbose_name='Athlete')),
            ],
            options={
                'verbose_name': 'Athlete for training',
                'verbose_name_plural': 'Athletes registrations for trainings',
                'ordering': ['time_registered'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'profile'), name='user_to_training'),
        ),
    ]
