# Generated by Django 3.1.5 on 2021-02-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitex', '0002_auto_20210111_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_registrations',
            field=models.BooleanField(default=True),
        ),
    ]
